feedback/urls.py
from django.urls import path
app_name = 'feedback'

from . import views
urlpatterns = [
    path('', views.home, name='root'),
    path('all/', views.FeedbackListView.as_view(), name='feedback-listing'),
    path('new/', views.FeedbackCreateView.as_view(), name='feedback-new'),
    path('<int:pk>/', views.FeedbackDetailView.as_view(), name='feedback-detail'),
    path('<int:pk>/update/', views.FeedbackUpdateView.as_view(), name='feedback-update'),
    path('<int:pk>/delete/', views.FeedbackDeleteView.as_view(), name='feedback-delete'),
    path('profiles/', views.ProfileUpdateView.as_view(), name='profile-detail'),
    path('change-password/', views.ChangePasswordView.as_view(), name='profile-password'),
]

smartfeedback/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from django.http import JsonResponse

admin.site.site_title = 'Smart Feedback'
admin.site.site_header = 'Smart Feedback Admin'
admin.site.index_title = 'Smart Feedback Admin'

def healthz(request):
    return JsonResponse({'status':'healthy'})

urlpatterns = [
    path('healthz/', healthz, name='healthz'),
    path('admin/', admin.site.urls),
    path('feedback/', include('feedback.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

feedback/models.py
from django.db import models

class Feedback(models.Model):
  body = models.TextField(default='', max_length=5120, null=False, blank=True)
  sentiment = models.CharField(max_length=512, null=False, blank=False)
  created_at = models.DateTimeField(auto_now_add=True, null=False)
  updated_at = models.DateTimeField(auto_now=True, null=False)
  class Meta:
    ordering = ['-id']

feedback/forms.py
from django import forms
from .models import Feedback
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class FeedbackForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={'placeholder': 'Comment', 'class': 'textarea'}
    ))
    class Meta:
        model = Feedback
        fields = ['body']

class PasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old Password",
        widget=forms.PasswordInput(
            attrs={'placeholder': '', 'class': 'input'}
    ))

    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(
            attrs={'placeholder': '', 'class': 'input'}
    ))

    new_password2 = forms.CharField(
        label="New Password Confirmation",
        widget=forms.PasswordInput(
            attrs={'placeholder': '', 'class': 'input'}
    ))

class UserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Username', 'class': 'input'}
    ))

    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'First Name', 'class': 'input'}
    ))

    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Last Name', 'class': 'input'}
    ))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']

feedback/views.py
from django.shortcuts import render
from .forms import UserForm, PasswordForm, FeedbackForm
from .models import Feedback
from .tasks import find_sentiment
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

def home(request):
  if not request.user.is_authenticated:
    return HttpResponseRedirect("/")
  return HttpResponseRedirect(reverse('feedback:feedback-listing'))

class FeedbackListView(LoginRequiredMixin, ListView):
    model = Feedback
    paginate_by = 100

class FeedbackDetailView(LoginRequiredMixin, DetailView):
    model = Feedback

class FeedbackUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Feedback
    form_class = FeedbackForm
    def get_success_url(self):
      return reverse('feedback:feedback-detail', kwargs={"pk": self.object.pk})

class FeedbackCreateView(SuccessMessageMixin, CreateView):
    model = Feedback
    form_class = FeedbackForm
    def get_success_message(self, cleaned_data):
        if not self.request.user.is_authenticated:
            return 'Thanks for the feedback!'
        else:
            return 'Saved'
    def get_success_url(self):
        if not self.request.user.is_authenticated:
            return "/"
        else:
            return reverse('feedback:feedback-detail', kwargs={"pk": self.object.pk})
    def form_valid(self, form):
        response = super().form_valid(form)
        obj = form.instance
        find_sentiment.delay_on_commit(obj.pk, obj.body)
        return response

class FeedbackDeleteView(DeleteView):
    model = Feedback
    success_url = reverse_lazy('feedback:feedback-listing')

class ChangePasswordView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    form_class = PasswordForm
    template_name = 'registration/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('feedback:profile-password')

class ProfileUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserForm
    success_message = "Successfully Updated Your Profile"
    success_url = reverse_lazy('feedback:profile-detail')
    def get_object(self, *args, **kwargs):
        return self.request.user

feedback/templates/feedback/feedback_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<section class="pf-v5-c-page__main-section pf-m-light">
  <h1>Feedback</h1>
  <p>Delete</p>
</section>

<section class="pf-v5-c-page__main-section pf-m-fill">
  <div class="center-form">
    <form method="post" class="pf-v5-c-form">
      {% csrf_token %}
      <section class="pf-v5-c-form__section" role="group">
        <p>Are you sure you want to delete? This cannot be undone.</p>
      </section>
      <div class="pf-v5-c-form__group pf-m-action">
        <div class="pf-v5-c-form__actions">
          <button class="pf-v5-c-button pf-m-danger" type="submit">Delete</button>
        </div>
      </div>
    </form>
  </div>

  <div class="mb-5 mt-5">
    <a href="{% url 'feedback:feedback-detail' object.id %}" class="button is-text">
      View
    </a>
  </div>
</section>

{% endblock %}

feedback/templates/feedback/feedback_detail.html
{% extends 'base.html' %}
{% block content %}

<section class="pf-v5-c-page__main-section pf-m-light">
  <h1>Feedback</h1>
  <p>Detail</p>
</section>

<section class="pf-v5-c-page__main-section pf-m-fill">
  {% include 'messages.html' with messages=messages %}
  <div class="pf-v5-c-card" id="card-basic-example">
    <div class="pf-v5-c-card__title">
      <h2 class="pf-v5-c-card__title-text">
      Comment {{ object.pk }}
      </h2>
    </div>
    <div class="pf-v5-c-card__body">
      <ul
        class="pf-v5-c-data-list"
        role="list"
        aria-label="Basic data list example"
        id="data-list-basic"
      >
        <li class="pf-v5-c-data-list__item">
          <div class="pf-v5-c-data-list__item-row">
            <div class="pf-v5-c-data-list__item-content">
              <div class="pf-v5-c-data-list__cell">
                <span>Comment</span>
              </div>
              <div class="pf-v5-c-data-list__cell">{{ object.body }}</div>
            </div>
          </div>
        </li>

        <li class="pf-v5-c-data-list__item">
          <div class="pf-v5-c-data-list__item-row">
            <div class="pf-v5-c-data-list__item-content">
              <div class="pf-v5-c-data-list__cell">
                <span>Sentiment</span>
              </div>
              <div class="pf-v5-c-data-list__cell">
                {% if object.sentiment == 'Positive' %}
                  <i class="fas fa-thumbs-up fa-lg" style="color: green;"></i>
                {% elif object.sentiment == 'Negative' %}
                  <i class="fas fa-thumbs-down fa-lg is-danger" style="color: red;"></i>
                {% else %}
                  {{ object.sentiment }}
                {% endif %}
              </div>
            </div>
          </div>
        </li>

        <li class="pf-v5-c-data-list__item">
          <div class="pf-v5-c-data-list__item-row">
            <div class="pf-v5-c-data-list__item-content">
              <div class="pf-v5-c-data-list__cell">
                <span>Created At (UTC)</span>
              </div>
              <div class="pf-v5-c-data-list__cell">
                {{ object.updated_at }}
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="pf-v5-c-card__footer">
      <a href="{% url 'feedback:feedback-update' object.id %}" class="pf-v5-c-button pf-m-secondary">
        Update
      </a>
      <a href="{% url 'feedback:feedback-delete' object.id %}" class="pf-v5-c-button pf-m-secondary">
        Delete
      </a>
      <a href="{% url 'feedback:feedback-listing' %}" class="pf-v5-c-button pf-m-secondary">
        View All
      </a>
    </div>
  </div>
</section>

{% endblock %}

feedback/templates/feedback/feedback_form.html
{% extends 'base.html' %}
{% block content %}

<section class="pf-v5-c-page__main-section pf-m-light">
  <h1>Feedback</h1>
  <p class="subtitle">
    {% if form.instance.id %}
    Update
    {% else %}
    New
    {% endif %}
  </p>
</section>

<section class="pf-v5-c-page__main-section pf-m-fill">
  <form method="post" class="pf-v5-c-form">
    {% csrf_token %}
    <section class="pf-v5-c-form__section" role="group">
      {% for field in form %}
        <div class="pf-v5-c-form__group">
          <div class="pf-v5-c-form__group-control">
            <span class="pf-v5-c-form-control pf-m-required">
              {{ field }}
            </span>
            {% if field.errors %}
              <small class="error has-text-danger">{{ field.errors|striptags }}</small>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </section>
    <div class="pf-v5-c-form__group pf-m-action">
      <div class="pf-v5-c-form__actions">
        <button class="pf-v5-c-button pf-m-primary" type="submit">Save</button>
      </div>
    </div>
  </form>

  <br />

  <div class="field is-grouped">
    {% if form.instance.pk %}
    <p class="control">
      <a href="{% url 'feedback:feedback-detail' object.id %}" class="button is-text">
        View
      </a>
    </p>
    {% endif %}

    <p class="control">
      <a href="{% url 'feedback:feedback-listing' %}" class="button is-text">
        View All
      </a>
    </p>
  </div>
</section>

{% endblock %}

feedback/templates/feedback/feedback_list.html
{% extends 'base.html' %}
{% block content %}

<section class="pf-v5-c-page__main-section pf-m-light">
  <h1>Feedback</h1>
  <p>Listing</p>
</section>

<section class="pf-v5-c-page__main-section pf-m-fill">
  <div class="field is-grouped">
    <p class="control">
      <a href="{% url 'feedback:feedback-new' %}" class="button is-secondary">
        New
      </a>
    </p>
  </div>

  <table
    class="pf-v5-c-table pf-m-grid-md"
    role="grid"
    aria-label="This is a simple table example"
    id="table-basic"
  >
    <caption class="pf-v5-c-table__caption">All Feedback</caption>
    <thead class="pf-v5-c-table__thead">
      <tr class="pf-v5-c-table__tr" role="row">
        <th class="pf-v5-c-table__th" role="columnheader" scope="col">Comment</th>
        <th class="pf-v5-c-table__th" role="columnheader" scope="col">Sentiment</th>
        <th class="pf-v5-c-table__th" role="columnheader" scope="col">Created At (UTC)</th>
      </tr>
    </thead>

    <tbody class="pf-v5-c-table__tbody" role="rowgroup">
      {% for obj in object_list %}
        <tr class="pf-v5-c-table__tr" role="row">
          <td class="pf-v5-c-table__td" role="cell" data-label="Comment" >
            <a href="{% url 'feedback:feedback-detail' obj.id %}" class="">
              {{ obj.body }}
            </a>
          </td>
          <td class="pf-v5-c-table__td" role="cell" data-label="Sentiment">
            {% if obj.sentiment == 'Positive' %}
              <i class="fas fa-thumbs-up fa-lg" style="color: green;"></i>
            {% elif obj.sentiment == 'Negative' %}
              <i class="fas fa-thumbs-down fa-lg is-danger" style="color: red;"></i>
            {% else %}
              {{ obj.sentiment }}
            {% endif %}
          </td>
          <td class="pf-v5-c-table__td" role="cell" data-label="Created At (UTC)">{{ obj.created_at }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if page_obj.paginator.num_pages > 1 %}
  <div class="pf-v5-c-pagination">
    <nav
      class="pf-v5-c-pagination__nav"
      aria-label="Pagination nav - top example"
    >
      {% if page_obj.has_previous %}
        <div class="pf-v5-c-pagination__nav-control pf-m-first">
          <a
            href="?page=1"
            class="pf-v5-c-button pf-m-plain"
            type="button"
            disabled
            aria-label="Go to first page"
          >
            <i class="fas fa-angle-double-left" aria-hidden="true"></i>
          </a>
        </div>
        <div class="pf-v5-c-pagination__nav-control pf-m-prev">
          <a
            href="?page={{ page_obj.previous_page_number }}"
            class="pf-v5-c-button pf-m-plain"
            type="button"
            disabled
            aria-label="Go to previous page"
          >
            <i class="fas fa-angle-left" aria-hidden="true"></i>
          </a>
        </div>
      {% endif %}

      <div class="pf-v5-c-pagination__nav-page-select">
        <span class="pf-v5-c-form-control">
          <input
            aria-label="Current page"
            type="number"
            value="{{ page_obj.number }}"
            disabled
          />
        </span>
        <span aria-hidden="true">of {{ page_obj.paginator.num_pages }}</span>
      </div>

      {% if page_obj.has_next %}
        <div class="pf-v5-c-pagination__nav-control pf-m-next">
          <a
            href="?page={{ page_obj.next_page_number }}"
            class="pf-v5-c-button pf-m-plain"
            type="button"
            aria-label="Go to next page"
          >
            <i class="fas fa-angle-right" aria-hidden="true"></i>
          </a>
        </div>
        <div class="pf-v5-c-pagination__nav-control pf-m-last">
          <a
            href="?page={{ page_obj.paginator.num_pages }}"
            class="pf-v5-c-button pf-m-plain"
            type="button"
            aria-label="Go to last page"
          >
            <i class="fas fa-angle-double-right" aria-hidden="true"></i>
          </a>
        </div>
      {% endif %}
    </nav>
  </div>
  {% endif %}
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Smart Feedback</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>💬</text></svg>" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{% static 'css/patternfly.css' %}" />
        <link rel="stylesheet" href="{% static 'css/patternfly-addons.css' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>

    <body>
        <div class="pf-v5-c-page">
          {% include 'navbar.html' %}
          <main class="pf-v5-c-page__main" tabindex="-1">
            {% block content %}
            {% endblock %}
            <!--
            <section class="pf-v5-c-page__main-section pf-m-fill">
              This section uses
              <code>.pf-m-fill</code> to fill the available space.
            </section>
            <section class="pf-v5-c-page__main-section pf-m-light pf-m-no-fill">
              This section uses
              <code>.pf-m-no-fill</code> to not fill the available space.
            </section>
            -->
          </main>
        </div>

        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.0/dist/cdn.min.js"></script>
        <script defer src="https://unpkg.com/htmx.org@1.9.12"></script>
        <script defer src="{% static 'js/app.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="pf-v5-c-page__main-section pf-m-light">
  {% if user.is_authenticated %}
    <h1 class="title">Welcome {{ user.first_name|default:user.username }}</h1>
    <p class="pt-4">
      <a class="button is-text" href="{% url 'feedback:feedback-listing' %}">See all feedback</a>
    </p>
  {% else %}
    <h1 class="title">Hello</h1>
    {% include 'messages.html' with messages=messages %}
    <a class="button is-text" href="{% url 'feedback:feedback-new' %}">Leave feedback</a>
  {% endif %}
</section>
{% endblock %}

templates/messages.html
{% if messages %}
<ul class="messages mt-5">
    {% for message in messages %}
      <li
        class="
               {% if message.tags %}{{ message.tags }}{% endif %}
               {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} pf-v5-u-danger-color-200
               {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} pf-v5-u-success-color-200
               {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %} pf-v5-u-warning-color-200
               {% else %} has-text-info
               {% endif %}
               ">
        {{ message }}
      </li>
    {% endfor %}
</ul>
{% endif %}

templates/navbar.html
{% load static %}
<header class="pf-v5-c-masthead" id="page-demo-basic-masthead">
  <div class="pf-v5-c-masthead__main">
      <a class="pf-v5-c-masthead__brand white" href="{% url 'feedback:root' %}" style="text-decoration: none;">
        <i class="fas fa-comment fa-2x" aria-hidden="true"></i>
        <div style="font-family: RedHatDisplay; font-weight: 400; font-size: 1.5rem; line-height: 1.3; padding-left: 0.5rem;">
          Smart Feedback
        </div>
      </a>
  </div>
  <div class="pf-v5-c-masthead__content">
    <div class="pf-v5-c-toolbar pf-m-full-height pf-m-static" id="page-demo-basic-masthead-toolbar">
        <div class="pf-v5-c-toolbar__content">
            <div class="pf-v5-c-toolbar__content-section">
                <div class="pf-v5-c-toolbar__group pf-m-icon-button-group pf-m-align-right pf-m-spacer-none pf-m-spacer-md-on-md">
                    <div class="pf-v5-c-toolbar__item pf-m-hidden-on-lg">
                        <button class="pf-v5-c-menu-toggle pf-m-plain" type="button" aria-expanded="false" aria-label="Actions">
                            <i class="fas fa-ellipsis-v" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
                <div class="pf-v5-c-toolbar__item pf-m-hidden pf-m-visible-on-sm">
                    {% if user.is_authenticated %}
                    <button class="pf-v5-c-menu-toggle pf-m-full-height" type="button" aria-expanded="false">
                        <span class="pf-v5-c-menu-toggle__icon">
                            <img class="pf-v5-c-avatar" alt="Avatar image" src="{% static 'images/img_avatar-light.svg' %}" />
                        </span>
                        <span class="pf-v5-c-menu-toggle__text">
                          <a class="white" href="{% url 'feedback:profile-detail' %}">
                            {{ user.get_username }}
                          </a>
                        </span>
                    </button>
                    {% else %}
                    <button class="pf-v5-c-menu-toggle pf-m-full-height" type="button" aria-expanded="false">
                      <a class="white" href="{% url 'login' %}">
                        Login
                      </a>
                    </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
  </div>
</header>